name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub (if needed)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ajeetraina/node-app:1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to server (replace with your deployment steps)
        # Here, you'd add steps to deploy your image to your server,
        # e.g., using SSH, Kubernetes, etc.
